### ISSUE TITLE
Program castle object, with health variable and shatter death

### ISSUE THREAD

**Issue by RyanBluth** [RyanBluth/Hurly-Burly-Puppet-Party#75]

**Comment by seleb** [comment]
Emma has started this.

**Comment by seleb** [comment]
Castle object correctly registers damage and changes to "destroyed" state; no visuals for destroyed castle yet (relies on a particle system being implemented)

**Comment by seleb** [comment]
Generalizes breakable structures.
Shatter still needs to be implemented.

**Comment by ecthurlow** [comment]
Breakable structures now generate dust particles upon death.
